### ISSUE TITLE
Login doesn't work in android app

### ISSUE THREAD

**Issue by AkilaEL** [deepstreamIO/ds-demo-pizza-tracker#5]
Hi there, 
I’m enable to get the deepstream authentication of the android app running, it doesn’t login on localhost. The login from a web app works though. 
here is how I connect to my local machine :  
try {
    client = factory.getClient("wss://IP_of_my_local_machine:6020");
      } catch (URISyntaxException e) {
     e.printStackTrace();

 JsonObject authData = new JsonObject();
 authData.addProperty("email", mEmail);
 authData.addProperty("password", mPassword);

 LoginResult result = client.login(authData);

I’m using:  android studio 3.5 , deepstream  3.2.5 , and in build.gradle , I call :
implementation 'io.deepstream:deepstream.io-client-java:2.0.4'

Thanks

**Comment by yasserf** [comment]
could it be because your using wss instead of ws?

**Comment by AkilaEL** [comment]
Thanks a lot, it solves the problem
